config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  resources :users do
    resources :companies, except: %I[index show]
  end


  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :companies, only: [:show, :index, :create]
    end
  end


  namespace :api do
    namespace :v1 do
      match :company_cash_update, to: 'users#company_cash_update', as: 'company_cash_update', via: %i(get post)
    end
  end

  get "*path" => redirect("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user

  validates :name, :country, :currency, presence: true
  validates :name, uniqueness: { case_sensitive: true }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :companies
  enum role: %I[student teacher]

  validates :name, :surname, presence: true
  validate :password_complexity
  validates :email, presence: true, uniqueness: true, length: { maximum: 64 }

  def password_complexity
    return if password.blank? || password =~ /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/

    errors.add :password, 'Complexity requirement. Minimum eight characters, at least 1 letter and 1 number'
  end

  def full_name
    [name, surname].compact.collect(&:capitalize).join(' ').strip
  end
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ActionController::Base
    respond_to :json
  end
end

app/controllers/api/v1/application_controller.rb
module Api
  module V1
    class ApplicationController < Api::ApplicationController
    end
  end
end

app/controllers/api/v1/companies_controller.rb
module Api
  module V1
    class CompaniesController < Api::V1::ApplicationController
      def index
        companies = Company.where(user: current_user)
        render json: Api::V1::CompaniesSerializer.new(companies).serialized_json, status: :ok
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = Company.new
  end

  def create
    company = Company.new(company_params)

    if company.valid? && company.save!
      @company = Company.new
      flash[:notice] = 'Company create successed'
    else
      flash[:alert] = company.errors.full_messages.join('; ')
    end
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def edit
    @company = Company.where(id: params[:id], user_id: current_user.id)&.first
  end

  def update
    company = Company.where(id: params[:id], user_id: current_user.id)&.first
    company.assign_attributes(company_params)

    if company.valid? && company.save!
      redirect_to root_path, notice: 'Company was successfully updated.'
    else
      flash[:alert] = company.errors.full_messages.join(', ')
    end

    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def destroy
    company = Company.where(id: params[:id], user_id: current_user.id)&.first

    if company.destroy
      flash[:notice] = 'Company destroyed'
    else
      flash[:alert] = company.errors.full_messages.join('; ')
    end

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private

  def all_companies
    @all_companies = Company.where(user: current_user)
  end

  def company_params
    params.require(:company).permit :id, :user_id, :name, :country, :currency
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @company = Company.new
    @companies = Company.where(user: current_user)
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters, if: :devise_controller?

    def update_resource(resource, params)
      resource.update_with_password(params)
    end

    protected

    def configure_permitted_parameters
      customer_key_attrs = %i[name surname photo role]

      devise_parameter_sanitizer.permit :sign_up, keys: customer_key_attrs
      devise_parameter_sanitizer.permit :account_update, keys: customer_key_attrs
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def cash_management
  end

  def company_cash_update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_error_type(type)
    case type.to_sym
    when :alert
      'warning'
    when :error
      'danger'
    when :notice
      'info'
    when :success
      'success'
    else
      type.to_s
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/companies/_modal_add_company.slim
- countries = ISO3166::Country.all.select{|el| ["Europe", "South America"].include? el.continent }.map(&:name)
- currency = ISO3166::Country.all.select{|el| ["Europe", "South America"].include? el.continent }.map(&:currency_code).uniq

#companyModal.modal.fade aria-hidden="true" aria-labelledby="companyModalLabel" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        h5#companyModalLabel.modal-title Enter companies's information
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
      .modal-body
        = form_for @company, url: user_companies_path(current_user),  authenticity_token: true, html: {class: 'form-horizontal', id: 'formAddCompany', role: 'form', remote: true } do |f|
          = f.text_field :name, label_as_placeholder: true, required: true, error: true, type: 'text', placeholder: '* Name', class: 'form-control'
          = f.select(:country, countries, {}, {class: 'form-control',  placeholder: '* Country'})
          = f.select(:currency, currency, {}, {class: 'form-control',  placeholder: '* Currency'})
          = f.hidden_field :user_id, value: current_user.id
          = f.button 'Save changes', id: 'submitAddAgentForFounder', class: 'button btn btn-success btn-prof', title: 'Please fill and check all fields', data: {toggle: 'tooltip', placement: 'bottom'}, type: :submit
          / .modal-footer
        / button.btn.btn-secondary data-dismiss="modal" type="button"  Close
        / button.btn.btn-primary type="button"  Save changes


          / Money::Currency.table.values.map{|el| el[:name]}

app/views/companies/_table_companies.slim
- current_user.reload
- companies = current_user.companies.order(created_at: :desc)
.row.justify-content-center
  .col-md-8.col-sm-8.col-lg-8.col-lx-8
    table.table.table-bordered
      thead
        tr.test_table
          th scope="col"  Name
          th scope="col"  Country
          th scope="col"  Currency
          th scope="col"  Action
      tbody
        - companies.each do |company|
          tr
            td= company.name
            td
              / = link_to 'Cash management',  cash_management_user_company_path(user_id: company.user.id, id: company.id)
              = link_to 'Cash management',  "#"
            td= company.country
            td= company.currency
            td.table-td-grid
              span.delete_company
                = link_to 'Delete',  user_company_path(user_id: company.user.id, id: company.id), remote: true, method: :delete, data: { confirm: 'Are you sure?' }
              span.edit_company
                = link_to 'Edit',  edit_user_company_path(user_id: company.user.id, id: company.id)

app/views/companies/create.js.slim
| $('#formAddCompanyModal').html("#{escape_javascript(render partial: 'companies/modal_add_company')}");
| $('#companiesTable').html("#{escape_javascript(render partial: 'companies/table_companies')}");
| $('#companyModal').modal('hide');
| $('.modal-backdrop').hide();

app/views/companies/destroy.js.slim
| $('#companiesTable').html("#{escape_javascript(render partial: 'companies/table_companies')}");

app/views/companies/edit.slim
- countries = ISO3166::Country.all.select { |el| ["Europe", "South America"].include? el.continent }.map(&:name)
- currency = ISO3166::Country.all.select { |el| ["Europe", "South America"].include? el.continent }.map(&:currency_code).uniq
.col-10.d-flex.justify-content-center
  .row.no-gutter
    .col-sm-12.col-lg-12.col-md-12.col-xl-12.vertical-align-2
      .flash-alerts-blocks
        = render partial: 'shared/flash_alerts'
  = form_for @company, url: user_company_path(current_user),  authenticity_token: true, html: {class: 'form-horizontal', id: 'formAddCompany', role: 'form'} do |f|
    = f.text_field :name, label_as_placeholder: true, required: true, error: false, type: "text", placeholder: "* Name", class: 'form-control'
    = f.select(:country, countries, {} , {class: 'form-control', placeholder: '* Country'})
    = f.select(:currency, currency, {}, {class: 'form-control', placeholder: '* Currency'})
    = f.hidden_field :user_id, value: current_user.id
    = f.button 'Update changes', id: 'submitAddAgentForFounder', class: 'button btn btn-success btn-prof', title: 'Please fill and check all fields', data: {toggle: 'tooltip', placement: "bottom"}, type: :submit

app/views/layouts/application.slim
doctype html
html
  head
    title StudyPlatform
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'reactEntrypointApp', 'data-turbolinks-track': 'reload'
  body
    - if user_signed_in?
      = render partial: 'shared/top_navigation'
    - else
      = render partial: 'shared/navigation_guest'
    #reactRoot
      = yield

app/views/main/index.html.slim
/ .row.no-gutter
  .col-sm-12.col-lg-12.col-md-12.col-xl-12.vertical-align-2
    .flash-alerts-blocks
      = render partial: 'shared/flash_alerts'
/ - if !!current_user && current_user.student?
  H2 Companies
  button type="button" class="btn btn-primary" data-toggle="modal" data-target="#companyModal"
    | Add companies +
  .companiesTable#companiesTable
    / = javascript_pack_tag 'companies'
    = render partial: 'companies/table_companies'
/ - if !!current_user && current_user.student?
  #formAddCompanyModal
    = render partial: 'companies/modal_add_company'

app/views/shared/_flash_alerts.slim
.col-sm-12.col-lg-12.col-md-12.col-xl-12
  .flash-alerts-blocks
    - flash.each do |type, message|
      div class="alert alert-#{flash_error_type(type)} alert-dismissible fade show" role="alert"
        = message
        button.close aria-label="Close" data-dismiss="alert" type="button"
          span aria-hidden="true"  &times;
    - flash.clear

javascript:
    $(document).ready(function () {
        $(".alert" ).fadeOut(6000)
    });

app/views/shared/_navigation_guest.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light.justify-content-end
  = link_to root_url, onclick: 'window.location.reload(true)', class: 'navbar-brand' do
    | StudyPlatform
  button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse.justify-content-end.main-navbar
    .navbar-right
      ul.navbar-nav.mr-auto
        li.nav-item
          = link_to 'Sign In', new_user_session_path, class: 'nav-link'
        li.nav-item
          = link_to 'Sign Up', new_user_registration_path, class: 'nav-link'

app/views/shared/_top_navigation.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to root_path,  onclick: 'window.location.reload(true)', class: 'navbar-brand' do
    | StudyPlatform
  button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse.justify-content-end.main-navbar
    ul.navbar-nav
      li.nav-item.dropdown
        a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
          = "#{current_user&.full_name} (#{current_user&.email})"
        .dropdown-menu aria-labelledby="navbarDropdown"
          = link_to edit_user_registration_path(current_user) do
            .dropdown-item
            | Profile
          .dropdown-divider
          = link_to 'Log out', destroy_user_session_path, class: 'dropdown-item', method: :delete

app/views/users/cash_management.html.erb
<%= javascript_pack_tag 'hello_react' %>